# Generated by Django 5.0.10 on 2024-12-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('room_description', models.CharField(blank=True, max_length=255, null=True)),
                ('room_size', models.IntegerField(blank=True, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField()),
                ('room_status', models.CharField(max_length=20)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
        ),
    ]
