# Generated by Django 5.0.10 on 2024-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_amenities_roomtype_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='facilities',
            field=models.JSONField(default=dict),
        ),
    ]
